#!/bin/sh

set -eu

find_scripts() {
    # Helper to find all scripts in the tree
    (
        # Any non-binary file which contains a given shebang
        git grep --cached -lIz '^#!.*'"$1"
        shift
        # Any file matching the provided globs
        git ls-files -z "$@"
    ) | sort -z | uniq -z
}

find_python_files() {
    find_scripts 'python3' '*.py'
}

find_python_files | xargs -0 ruff check --quiet --force-exclude
find_python_files | xargs -0 mypy --no-error-summary
pytest -vv
