#!/bin/sh

set -eu

# run static code checks like pyflakes and pep8
PYFILES=$(git grep -lI '^#!.*python')
python3 -m pyflakes $PYFILES

# FIXME: Fix code for the warnings and re-enable them
python3 -m pycodestyle --ignore E722,E501,W504,E402 $PYFILES

./test-bots
