#!/usr/bin/env python3

# This file is part of Cockpit.
#
# Copyright (C) 2023 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

# Update COCKPIT_REPO_COMMIT to cockpit HEAD automatically, defaults to
# Makefile as input optionally the full path can be provided. (For example
# Anaconda uses ui/webui/Makefile.am).

import argparse
import re

from lib import git
from lib.github import GitHub

GIT_URL_RE = r'COCKPIT_REPO_URL\s*=\s*(.*)'
GIT_COMMIT_RE = r'COCKPIT_REPO_COMMIT\s*=\s*(.*)'


def main() -> None:
    parser = argparse.ArgumentParser(description="Update COCKPIT_REPO_COMMIT for cockpit projects")
    parser.add_argument("--dry", action="store_true", help="Dry run to validate this task if supported")
    parser.add_argument("context", nargs="?", help="Path to makefile (default: Makefile)")

    args = parser.parse_args()

    cockpit_repo_url = 'https://github.com/cockpit-project/cockpit.git'
    cockpit_repo_commit = 'HEAD'
    makefile = args.context or 'Makefile'

    with open(makefile) as fp:
        content = fp.read()

    m = re.search(GIT_URL_RE, content)
    if m:
        cockpit_repo_url = m.group(1)

    m = re.search(GIT_COMMIT_RE, content)
    if m:
        cockpit_repo_commit = m.group(1)

    # Figure out latest cockpit tip commit
    commit = cockpit_repo_commit.partition('#')[0].strip()
    with git.temporary_checkout(cockpit_repo_url):
        git_describe = git.describe()
        git_head = git.get_current_head()
        git_shortlog = git.shortlog(
            f'{commit}...', 'pkg/lib', 'test/common', 'test/static-code', 'tools/node-modules'
        ).strip()

    try:
        # when HEAD is not tagged, this looks like "290-9-g4a6d86f5b"
        tag, commits, _ = git_describe.split('-')
        comment = f'{git_head} # {tag} + {commits} commits'
    except ValueError:
        # when HEAD is tagged, use that name
        comment = f'{git_head} # {git_describe}'

    new_content = content.replace(cockpit_repo_commit, comment)
    if content == new_content:
        print("COCKPIT_REPO_COMMIT is already up to date, nothing to do")
        return

    with open(makefile, 'w') as fp:
        fp.write(new_content)

    title = f"Makefile: Update Cockpit lib to {git_head[:32]}"
    git.add(makefile)
    if not git.changes_staged():
        # No change?  No PR.
        return
    git.commit(title)

    github = GitHub()
    branch = git.push(github, 'cockpit-lib', dry_run=args.dry)
    pr_number = github.create_pull_request(branch, title, body=git_shortlog, dry_run=args.dry)
    git.amend_and_forcepush(github, branch, closes=pr_number, dry_run=args.dry)


if __name__ == '__main__':
    main()
