#!/usr/bin/env python3

# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import argparse
import json
import os
import shlex
import subprocess
import sys
import time

from lib import github
from lib.aio.jsonutil import get_int, get_str, typechecked
from lib.constants import BASE_DIR

# default for refresh-days
DAYS = 7

REFRESH_30 = {"refresh-days": 30}

# stable/old OSes don't need to be refreshed as often
REFRESH = {
    "arch": {},
    "centos-9-bootc": {},
    "centos-9-stream": {},
    "centos-10": {},
    "debian-testing": {},
    "debian-trixie": {},
    "fedora-42": {},
    "fedora-43": {},
    "fedora-44": {},
    "fedora-44-boot": {},
    "fedora-44-anaconda-payload": REFRESH_30,
    "fedora-coreos": {},
    "fedora-rawhide": {},
    "fedora-rawhide-boot": {},
    "fedora-rawhide-anaconda-payload": REFRESH_30,
    "opensuse-tumbleweed": {},
    "ubuntu-2204": {},
    "ubuntu-2404": {},
    "ubuntu-2604": {},
    "ubuntu-stable": {},
    "rhel-8-8": REFRESH_30,
    "rhel-8-10": {},
    "rhel-9-2": REFRESH_30,
    "rhel-9-4": REFRESH_30,
    "rhel-9-6": REFRESH_30,
    "rhel-9-8": REFRESH_30,
    "rhel-9-9": {},
    "rhel-10-0": REFRESH_30,
    "rhel-10-2": REFRESH_30,
    "rhel-10-3": {},
    "services": REFRESH_30,
}


def main() -> int:
    parser = argparse.ArgumentParser(description='Ensure necessary issue exists for image refresh')
    parser.add_argument('-v', '--verbose', action="store_true", default=False,
                        help="Print verbose information")
    parser.add_argument('--dry-run', '-n', action="store_true", default=False,
                        help="Show what would be done, but don't do it")
    parser.add_argument("image", nargs="?")
    opts = parser.parse_args()
    api = github.GitHub()

    try:
        scan(api, opts.image, opts.verbose, dry=opts.dry_run)
    except RuntimeError as ex:
        sys.stderr.write("image-trigger: " + str(ex) + "\n")
        return 1

    return 0


def last_update(pathspec: str, ref: str = "HEAD", verbose: bool = False) -> tuple[str, int] | None:
    """Return (commit_sha, age_in_days) of the last commit touching pathspec, or None."""
    cmd = ["git", "log", "--max-count=1", "--pretty=format:%ct %H", ref, "--", pathspec]
    if verbose:
        sys.stderr.write("+ " + shlex.join(cmd) + "\n")
    output = subprocess.check_output(cmd, cwd=BASE_DIR, text=True)
    if verbose:
        sys.stderr.write("> " + output + "\n")

    parts = output.split(maxsplit=1)
    try:
        timestamp = int(parts[0])
    except (ValueError, IndexError):
        return None
    sha = parts[1].strip() if len(parts) > 1 else ""

    return sha, int((time.time() - timestamp) / 86400)


def scan(api: github.GitHub, force: str | None, verbose: bool, dry: bool = False) -> None:
    subprocess.check_call(["git", "fetch", "origin", "main"])

    issues = {
        get_str(issue, "title"): get_int(issue, "number")
        for issue in api.issues(state="open")
    }

    for (image, options) in REFRESH.items():
        update = last_update(os.path.join("images", image), "origin/main", verbose)

        if force:
            if image != force:
                continue

        if update is not None:
            sha, age = update
            if not force and age < options.get("refresh-days", DAYS):
                continue
            body = f"Last updated in {sha}, {age} days ago.\n"
        else:
            body = "No previous image refresh found.\n"

        title = f"Image refresh for {image}"
        if title in issues:
            sys.stderr.write(f'#{issues[title]}: {title} (already open)\n')
            continue

        data = {"title": title, "body": body, "labels": ["bot"]}
        if dry:
            print(f'** Would open issue on {api.repo}', json.dumps(data, indent=4))
        else:
            issue = typechecked(api.post("issues", data), dict)
            number = get_int(issue, "number")
            api.post(f"issues/{number}/comments", {"body": f"/image-refresh {image}"})
            sys.stderr.write(f'#{number}: image-refresh {image}\n')


if __name__ == '__main__':
    sys.exit(main())
