#!/usr/bin/env python3

# This file is part of Cockpit.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import argparse
import json
import os
import random
import shlex
import subprocess
import sys
import time
from collections.abc import Sequence

from lib import github
from lib.aio.jsonutil import JsonObject, get_str, typechecked
from lib.constants import BASE_DIR

# default for refresh-days
DAYS = 7

REFRESH_30 = {"refresh-days": 30}

# stable/old OSes don't need to be refreshed as often
REFRESH = {
    "arch": {},
    "centos-9-bootc": {},
    "centos-9-stream": {},
    "centos-10": {},
    "debian-testing": {},
    "debian-trixie": {},
    "fedora-42": {},
    "fedora-43": {},
    "fedora-44": {},
    "fedora-44-boot": {},
    "fedora-44-anaconda-payload": REFRESH_30,
    "fedora-coreos": {},
    "fedora-rawhide": {},
    "fedora-rawhide-boot": {},
    "fedora-rawhide-anaconda-payload": REFRESH_30,
    "opensuse-tumbleweed": {},
    "ubuntu-2204": {},
    "ubuntu-2404": {},
    "ubuntu-stable": {},
    "rhel-8-8": REFRESH_30,
    "rhel-8-10": {},
    "rhel-9-2": REFRESH_30,
    "rhel-9-4": REFRESH_30,
    "rhel-9-6": REFRESH_30,
    "rhel-9-8": {},
    "rhel-10-0": REFRESH_30,
    "rhel-10-2": {},
    "services": REFRESH_30,
}


def main() -> int:
    parser = argparse.ArgumentParser(description='Ensure necessary issue exists for image refresh')
    parser.add_argument('-v', '--verbose', action="store_true", default=False,
                        help="Print verbose information")
    parser.add_argument("image", nargs="?")
    opts = parser.parse_args()
    api = github.GitHub()

    try:
        scan(api, opts.image, opts.verbose)
    except RuntimeError as ex:
        sys.stderr.write("image-trigger: " + str(ex) + "\n")
        return 1

    return 0


# Check if the given files that match @pathspec are stale
# and haven't been updated in @days.
def stale(days: int, pathspec: str, ref: str = "HEAD", verbose: bool = False) -> bool:
    cmd = ["git", "log", "--max-count=1", "--pretty=format:%ct", ref, "--", pathspec]
    if verbose:
        sys.stderr.write("+ " + shlex.join(cmd) + "\n")
    output = subprocess.check_output(cmd, cwd=BASE_DIR, text=True)
    if verbose:
        sys.stderr.write("> " + output + "\n")

    try:
        timestamp = int(output)
    except ValueError:
        timestamp = 0

    # We randomize when we think this should happen over a day
    offset = days * 86400
    due = time.time() - random.randint(offset - 43200, offset + 43200)

    return timestamp < due


def would(*args: object) -> None:
    print('\n** Would', *args)


def create_issue(
    api: github.GitHub,
    title: str,
    body: str,
    item: str,
    context: str | None = None,
    items: Sequence[str] = (),
    state: str = "open",
    since: int | None = None,
    dry: bool = False
) -> JsonObject:
    if context:
        item = f"{item} {context}".strip()

    if since:
        # don't let all bots pass the deadline in the same second, to avoid many duplicates
        since += random.randint(-3600, 3600)

    for issue in api.issues(state=state, since=since):
        checklist = github.Checklist(get_str(issue, "body", None))
        if item in checklist.items:
            return issue

    if not items:
        items = [item]
    checklist = github.Checklist(body)
    for x in items:
        checklist.add(x)
    data = {
        "title": title,
        "body": checklist.body,
        "labels": ["bot"]
    }

    if dry:
        would(f'open issue on {api.repo}', json.dumps(data, indent=4))
        return data
    else:
        return typechecked(api.post("issues", data), dict)


def scan(api: github.GitHub, force: str | None, verbose: bool) -> None:
    subprocess.check_call(["git", "fetch", "origin", "main"])
    for (image, options) in REFRESH.items():
        perform = False

        if force:
            perform = image == force
        else:
            days = options.get("refresh-days", DAYS)
            perform = stale(days, os.path.join("images", image), "origin/main", verbose)

        if perform:
            text = f"Image refresh for {image}"
            issue = create_issue(api, text, text, "image-refresh", image)
            sys.stderr.write(f'#{issue["number"]}: image-refresh {image}\n')


if __name__ == '__main__':
    sys.exit(main())
