#!/usr/bin/env python3

# This file is part of Cockpit.
#
# Copyright (C) 2016 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import os
import subprocess
import sys

import task
from task import github, testmap, REDHAT_STORES

from machine.machine_core.directories import BOTS_DIR


sys.dont_write_bytecode = True


def run(image, verbose=False, **kwargs):
    if not image:
        raise RuntimeError("no image specified")

    triggers = testmap.tests_for_image(image)

    # Cleanup any extraneous disk usage elsewhere
    subprocess.check_call([os.path.join(BOTS_DIR, "vm-reset")])

    cmd = [os.path.join(BOTS_DIR, "image-create"), "--verbose", "--upload"]
    # these images are not freely redistributable, keep them Red Hat internal
    if image.startswith("rhel") or image.startswith("windows"):
        # FIXME: Move this to image-upload and try all stores
        cmd += ["--store", REDHAT_STORES[0]]
    cmd += [image]

    os.environ['VIRT_BUILDER_NO_CACHE'] = "yes"
    ret = subprocess.call(cmd)
    if ret:
        return ret

    branch = task.branch(image, "images: Update {0} image".format(image), pathspec="images", **kwargs)
    if branch:
        pull = task.pull(branch, labels=['bot', 'no-test'], run_tests=False, **kwargs)

        # Trigger this pull request
        api = github.GitHub()
        head = pull["head"]["sha"]
        for trigger in triggers:
            api.post("statuses/{0}".format(head), {"state": "pending", "context": trigger,
                                                   "description": github.NOT_TESTED_DIRECT})


if __name__ == '__main__':
    task.main(function=run, title="Refresh image")
