# Default configuration for job-runner

# This file contains the default settings for job-runner and will always be
# read in order to get the defaults.  It is also meant to act as a rudimentary
# form of documentation for the options which are available.

# Anything in this file can be overridden by installing a file with a similar
# format in one of the following locations (in order of precedence):
#   - the path specified via `--config-file`
#   - the path specified via the `JOB_RUNNER_CONFIG` environment variable
#   - XDG_CONFIG_HOME/cockpit-dev/job-runner.toml

# The defaults from this file are merged with overrides from the first such
# file found.

# The default configuration will use your personal GitHub user account (via
# your personal access token in ~/.config/cockpit-dev/github-token, if
# available) to read from GitHub but won't post unless you set `post = true`,
# but in that case, as a safety measure, you must also explicitly configure a
# `token =` to explicitly indicate which account you want to use.

[container]
command = ['podman']
run-args = [
  # '--device=/dev/kvm'
]
default-image = 'ghcr.io/cockpit-project/tasks:latest'

[container.secrets]
# see podman-secret(1)
# github-token = ['--secret=github-token']

[logs]
driver='local'   # 's3' or 'local'

[logs.s3]
# hint: podman run --rm --net=host quay.io/minio/minio server /var
url = 'http://127.0.0.1:9000/tmp/'
# different URL for GitHub status links if the S3 `url` above is not publicly accessible
# proxy_url = 'http://logs.example.com/tmp/'
key = {access='minioadmin', secret='minioadmin'}
user-agent = 'job-runner (cockpit-project/bots)'
acl = 'public-read'

[logs.local]
# hint: python -m http.server -b 127.0.0.1 -d ~/.cache/cockpit-dev/job-runner-logs
dir = '~/.cache/cockpit-dev/job-runner-logs'
link = 'http://127.0.0.1:8000/'

[forge]
default = 'github'

[forge.github]
driver = 'github'
clone-url = 'https://github.com/'
api-url = 'https://api.github.com/'
user-agent = 'job-runner (cockpit-project/bots)'
# If you set `post = true` then you must explicitly set a token here as well
post = false  # whether to post statuses, open issues, etc.
# token = 'ghp_XXX'

[forge.codeberg]
driver = 'github'
clone-url = 'https://codeberg.org/'
api-url = 'https://codeberg.org/api/v1'
post = false
user-agent = 'job-runner (cockpit-project/bots)'
