#!/usr/bin/env python3

# Copyright (C) 2026 Red Hat, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

import argparse
import json
import logging
import time
from pathlib import Path
from typing import TYPE_CHECKING

import boto3
import botocore.exceptions

from lib.aio.jsonutil import get_str, typechecked
from lib.launch_ec2 import REGION, launch_instance

if TYPE_CHECKING:
    from boto3.ec2 import EC2Client

logger = logging.getLogger(__name__)


def watch_instance(ec2: EC2Client, instance_id: str, start: float = 0) -> None:
    prev_state = None
    while True:
        try:
            desc = ec2.describe_instances(InstanceIds=[instance_id])
        except botocore.exceptions.ClientError as exc:
            # https://docs.aws.amazon.com/ec2/latest/devguide/eventual-consistency.html
            if exc.response['Error']['Code'] == 'InvalidInstanceID.NotFound':
                elapsed = time.clock_gettime(time.CLOCK_BOOTTIME) - start
                if elapsed < 30:
                    print(f'instance not yet visible after {elapsed:.0f}s')
                    time.sleep(2.5)
                    continue
                if elapsed > 30 * 60:
                    break
            raise
        instance = desc['Reservations'][0]['Instances'][0]
        state = instance['State']['Name']
        ip = instance.get('PublicIpAddress', '')
        private_ip = instance.get('PrivateIpAddress', '')

        if state != prev_state:
            parts = [state]
            if ip:
                parts.append(f'public={ip}')
            if private_ip:
                parts.append(f'private={private_ip}')
            print(' '.join(parts))
            prev_state = state

        if state == 'terminated':
            break

        time.sleep(2.5)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('job_json', help='Job specification as JSON string')
    parser.add_argument('--ami', help='FCOS AMI ID (default: latest)')
    parser.add_argument('--instance-type', default='m8id.large')
    parser.add_argument('--ssh-key', type=Path, help='SSH public key file to authorize for the core user')
    parser.add_argument('--timeout-min', type=int, default=150, help='Instance timeout in minutes (default: 150)')
    parser.add_argument('--debug', action='store_true', help='Enable debug logging')
    args = parser.parse_args()

    logging.basicConfig(level=logging.DEBUG if args.debug else logging.INFO)

    job = typechecked(json.loads(args.job_json), dict)
    slug = get_str(job, 'slug')
    logger.debug('slug: %r', slug)

    ec2 = boto3.client('ec2', region_name=REGION)
    sts = boto3.client('sts', region_name=REGION)

    instance_id = launch_instance(
        ec2, sts, job,
        instance_type=args.instance_type,
        timeout_min=args.timeout_min,
        ami=args.ami,
        ssh_keys=args.ssh_key.read_text().strip().splitlines() if args.ssh_key else (),
    )

    try:
        print(f'launched {instance_id}')
        watch_instance(ec2, instance_id, start=time.clock_gettime(time.CLOCK_BOOTTIME))
    finally:
        ec2.terminate_instances(InstanceIds=[instance_id])
        watch_instance(ec2, instance_id)


if __name__ == '__main__':
    main()
