#!/bin/sh

set -eu

usage()
{
    echo "usage: make-checkout [-v] [--rebase BRANCH] --repo REPO REF [REVISION]" >&2
}

eval set -- "$(getopt -o vh -l repo:,rebase:,help,verbose -- "$@")"

while true; do
  case "${1:-}" in
    -v|--verbose) set -x ;;
    -h|--help) usage; exit 0 ;;
    --repo) shift; REPO="$1" ;;
    --rebase) shift; REBASE="$1" ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
  shift
done

if [ $# -gt 2 ] || [ $# -lt 1 ] || [ -z "${REPO:-}" ]; then
    usage
    exit 1
fi

REF="$1"
REV=${2:-"FETCH_HEAD"}

TARGET_DIR="make-checkout-workdir"
# avoid failures with non-writable subdirectories
if [ -e "$TARGET_DIR" ]; then
    chmod -R u+w "$TARGET_DIR"
    rm -rf "$TARGET_DIR"
fi

git clone "https://github.com/$REPO" "$TARGET_DIR"
cd "$TARGET_DIR"

git fetch origin "$REF"
git checkout --detach "$REV"

if [ -n "${REBASE:-}" ]; then
    git fetch origin "$REBASE"
    SHA=`git rev-parse "origin/$REBASE"`
    echo "Rebasing onto origin/$REBASE $SHA ..."
    git rebase "origin/$REBASE"
fi
