#!/usr/bin/env python3

# This file is part of Cockpit.
#
# Copyright (C) 2017 Red Hat, Inc.
#
# Cockpit is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# Cockpit is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Cockpit; If not, see <http://www.gnu.org/licenses/>.

import argparse
import textwrap
from datetime import datetime, timedelta, timezone

from lib import git
from lib.aio.jsonutil import get_int, get_str
from lib.github import GitHub

# How long until a known issue is treated as stale
STALE = timedelta(days=21)


def main() -> None:
    parser = argparse.ArgumentParser(description="Close stale known issues")
    parser.add_argument("-n", "--dry-run", action="store_true", help="Dry run to validate this task if supported")
    args = parser.parse_args()

    github = GitHub()
    now = datetime.now(timezone.utc)
    head = git.get_current_head()
    filed = 0

    # Get all the open known issues
    issues = github.issues(labels=["knownissue"])
    for issue in issues:
        number = get_int(issue, "number")

        updated_str = get_str(issue, "updated_at", None) or get_str(issue, "created_at", None)
        if not updated_str:
            continue

        updated = datetime.fromisoformat(updated_str)
        days = (now - updated).days
        print(f"\nConsidering #{number} which had last comment {updated_str}, {days} days ago...")

        # Don't touch recently updated issues
        if updated > now - STALE:
            print("  skipping: not stale yet")
            continue

        # Create a pull request from these changes
        issue_title = get_str(issue, 'title')
        title = f"naughty: Close {number}: {issue_title}"
        body = f"Known issue which has not occurred in {days} days\n\n{issue_title}\n\nFixes #{number}"

        print(f"filing PR: {title}\n{textwrap.indent(body, '    ')}\n")
        filed += 1
        if args.dry_run:
            continue

        # Start from our original HEAD and remove matching naughties
        git.detach_head(head)
        git.rm(f"naughty/*/{number}-*")

        # Even if somehow no files are removed we should still file an empty
        # pull request to get the issue closed, otherwise we'll never find out
        # about it.
        git.commit(f"{title}\n\n{body}", allow_empty=True)

        branch = git.push(github, f"naughty-prune-{number}")
        pr_number = github.create_pull_request(branch, body=body, title=title)
        git.amend_and_forcepush(github, branch)
        github.comment(pr_number,
                       "Please comment on the upstream distro bug manually before accepting this "
                       "pull request.\n\nIf you wish to keep this known issue open, then update it")

    print(f"{filed} PRs filed")


if __name__ == '__main__':
    main()
