#!/usr/bin/env python3

# Copyright (C) 2026 Red Hat, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

"""Log in to AWS via SAML using a web browser.

Opens a WebKitGTK window to the IdP, intercepts the SAML assertion,
exchanges it for temporary AWS credentials via STS, and caches them to disk
for use by image-download.
"""

import argparse
import logging
import sys

import gi  # type: ignore [import-untyped]

from lib.ansi import GREEN, RESET
from lib.gssapi_saml_sts import (
    TARGETS,
    AuthError,
    aws_sts_assume_role,
    cache_path,
    save_to_cache,
)

logger = logging.getLogger(__name__)


def main() -> None:
    parser = argparse.ArgumentParser(description='Log in to AWS via SAML using a web browser')
    parser.add_argument('-d', '--debug', action='store_true', help='Enable debug logging')
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG, format='%(name)s: %(message)s')

    gi.require_version('Gtk', '4.0')
    gi.require_version('JavaScriptCore', '6.0')
    gi.require_version('WebKit', '6.0')

    from gi.repository import GLib, Gtk, JavaScriptCore, WebKit  # type: ignore [import-untyped]

    target, = TARGETS.values()  # only one for now
    loop = GLib.MainLoop()

    def on_saml_message_received(_manager: WebKit.UserContentManager, message: JavaScriptCore.Value) -> None:
        saml_assertion = message.to_string()
        logger.debug('captured SAML assertion (%d bytes)', len(saml_assertion))
        xml = aws_sts_assume_role(target.role_arn, target.provider_arn, saml_assertion, target.max_session_duration)

        role_name = target.role_arn.rsplit('/', 1)[-1]
        try:
            _key, expiration = save_to_cache(role_name, xml)
        except AuthError as exc:
            sys.exit(str(exc))

        local = expiration.astimezone()
        print(f'\n{GREEN}STS credentials saved to {cache_path(role_name)}\nValid until {local:%c}{RESET}\n')
        loop.quit()

    content_manager = WebKit.UserContentManager()

    # Monkey-patch the page to post the SAML assertion back to us
    content_manager.register_script_message_handler('saml')
    content_manager.connect('script-message-received::saml', on_saml_message_received)
    content_manager.add_script(
        WebKit.UserScript(
            r'''
                // Keycloak's has a 2s setTimeout before following a link
                // to the SAML POST binding page.  Redirect immediately.
                const finish = document.getElementById('finishLoginLink');
                if (finish) {
                    location.href = finish.href;
                }

                // Capture the response from the POST binding and don't redirect.
                const input = document.querySelector('input[name="SAMLResponse"]');
                if (input) {
                    window.webkit.messageHandlers.saml.postMessage(input.value);
                    input.form.action = '';
                }
            ''',
            WebKit.UserContentInjectedFrames.TOP_FRAME,
            WebKit.UserScriptInjectionTime.END,
        )
    )

    webview = WebKit.WebView(user_content_manager=content_manager)
    webview.load_uri(target.idp_url)

    win = Gtk.Window(
        title='SAML Login',
        default_width=1024,
        default_height=768,
        child=webview,
    )
    win.connect('close-request', lambda _win: loop.quit())
    win.present()

    loop.run()


if __name__ == '__main__':
    main()
