#! /bin/bash
set -e

# remove cockpit distro packages, testing with upstream master
rpm --erase --verbose cockpit cockpit-ws cockpit-bridge cockpit-system

/var/lib/testvm/fedora.install "$@"

# HACK: packagekit.service hangs on stop; https://bugzilla.redhat.com/show_bug.cgi?id=1717185
mkdir -p /etc/systemd/system/packagekit.service.d
printf '[Service]\nTimeoutStopSec=5\n' > /etc/systemd/system/packagekit.service.d/timeout.conf
