class AMQPError(Exception): ...
class AMQPConnectionError(AMQPError): ...
class ChannelClosedByBroker(AMQPError):
    reply_code: int
    reply_text: str
    def __init__(self, reply_code: int, reply_text: str) -> None: ...
