name: daily
on:
  schedule:
    - cron: '30 1 * * *'
  # can be run manually on https://github.com/cockpit-project/bots/actions
  workflow_dispatch:
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secrets
        run: echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log into quay
        run: docker login -u="${{ secrets.QUAY_BOTUSER }}" -p="${{ secrets.QUAY_TOKEN }}" quay.io

      - name: Synchronize container image mirror
        run: ./sync-quay

      - name: Trigger image refreshes
        run: ./image-trigger

      - name: Trigger naughty-prune
        run: ./naughty-trigger
