name: image refresh trigger
on:
  schedule:
    # this is UTC-4
    - cron: '30 22 * * *'
  # can be run manually on https://github.com/cockpit-project/bots/actions
  workflow_dispatch:
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secrets
        run: echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger image refreshes
        run: ./image-trigger
