name: prune naughties
on:
  schedule:
    - cron: '30 1 * * *'
  # can be run manually on https://github.com/cockpit-project/bots/actions
  workflow_dispatch:
jobs:
  maintenance:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
      contents: write
    steps:
      - name: Set up secrets
        run: echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run naughty-prune
        run: |
          git config --global user.name "GitHub Workflow"
          git config --global user.email "cockpituous@cockpit-project.org"
          ./naughty-prune --verbose
